# Generated by Django 5.2.16 on 2026-07-23 09:34

import django.db.models.deletion
import knowledge_base.models
import pgvector.django.vector
from pgvector.django import VectorExtension
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='KnowledgeFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('color', models.CharField(default='#4F46E5', max_length=7)),
                ('is_favorite', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='knowledge_base.knowledgefolder')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=240)),
                ('file', models.FileField(max_length=500, upload_to=knowledge_base.models.knowledge_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('checksum', models.CharField(db_index=True, max_length=64)),
                ('extracted_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='processing', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('is_favorite', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_documents', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='knowledge_base.knowledgefolder')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=240)),
                ('content', models.TextField(blank=True)),
                ('content_format', models.CharField(default='markdown', max_length=20)),
                ('context_type', models.CharField(choices=[('general', 'General'), ('subject', 'Subject'), ('topic', 'Topic'), ('project', 'Project')], default='general', max_length=20)),
                ('context_label', models.CharField(blank=True, max_length=160)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='knowledge_base.knowledgefolder')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('note', 'Note'), ('document', 'Document')], max_length=20)),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_chunks', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge_base.knowledgedocument')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge_base.knowledgenote')),
            ],
            options={
                'ordering': ['source_type', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeNoteVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=240)),
                ('content', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_note_versions', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='knowledge_base.knowledgenote')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('color', models.CharField(default='#7C3AED', max_length=7)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='knowledgenote',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='notes', to='knowledge_base.knowledgetag'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='documents', to='knowledge_base.knowledgetag'),
        ),
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(max_length=40)),
                ('code', models.TextField()),
                ('is_favorite', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_snippets', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snippets', to='knowledge_base.knowledgefolder')),
                ('tags', models.ManyToManyField(blank=True, related_name='snippets', to='knowledge_base.knowledgetag')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeAIInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('ask', 'Ask knowledge base'), ('summary', 'Summary'), ('flashcards', 'Flashcards'), ('interview', 'Interview questions'), ('revision', 'Revision plan'), ('explain', 'Explanation')], max_length=30)),
                ('model', models.CharField(max_length=120)),
                ('source_ids', models.JSONField(default=list)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('succeeded', models.BooleanField(default=False)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_ai_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action', '-created_at'], name='knowledge_b_user_id_5cb0be_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentHighlight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('start_offset', models.PositiveIntegerField(blank=True, null=True)),
                ('end_offset', models.PositiveIntegerField(blank=True, null=True)),
                ('quote', models.TextField()),
                ('annotation', models.TextField(blank=True)),
                ('color', models.CharField(default='#FDE68A', max_length=7)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_highlights', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='knowledge_base.knowledgedocument')),
            ],
            options={
                'ordering': ['page_number', 'created_at'],
                'indexes': [models.Index(fields=['owner', 'document', 'page_number'], name='knowledge_b_owner_i_9d6fc7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgefolder',
            index=models.Index(fields=['owner', 'parent', 'name'], name='knowledge_b_owner_i_53276c_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['owner', 'source_type'], name='knowledge_b_owner_i_2eebe5_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['note', 'chunk_index'], name='knowledge_b_note_id_7942fa_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['document', 'chunk_index'], name='knowledge_b_documen_f5b49b_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgechunk',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('document__isnull', True), ('note__isnull', False)), models.Q(('document__isnull', False), ('note__isnull', True)), _connector='OR'), name='knowledge_chunk_has_one_source'),
        ),
        migrations.AddConstraint(
            model_name='knowledgenoteversion',
            constraint=models.UniqueConstraint(fields=('note', 'version'), name='unique_knowledge_note_version'),
        ),
        migrations.AddConstraint(
            model_name='knowledgetag',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_knowledge_tag_per_user'),
        ),
        migrations.AddIndex(
            model_name='knowledgenote',
            index=models.Index(fields=['owner', 'is_archived', '-updated_at'], name='knowledge_b_owner_i_62367e_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgenote',
            index=models.Index(fields=['owner', 'folder', '-updated_at'], name='knowledge_b_owner_i_a36ef7_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['owner', 'status', '-updated_at'], name='knowledge_b_owner_i_5980dc_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['owner', 'folder', '-updated_at'], name='knowledge_b_owner_i_cd90ce_idx'),
        ),
        migrations.AddIndex(
            model_name='codesnippet',
            index=models.Index(fields=['owner', 'language', '-updated_at'], name='knowledge_b_owner_i_9af3a5_idx'),
        ),
    ]
