# Generated by Django 5.2.16 on 2026-07-22 15:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("roadmaps", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyResource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=240)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[("youtube", "YouTube")],
                        default="youtube",
                        max_length=20,
                    ),
                ),
                ("external_url", models.URLField(max_length=1000)),
                ("youtube_video_id", models.CharField(db_index=True, max_length=20)),
                ("channel_name", models.CharField(blank=True, max_length=180)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_study_resources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_resources",
                        to="roadmaps.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudyNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("timestamp_seconds", models.PositiveIntegerField(default=0)),
                ("content", models.TextField()),
                (
                    "content_format",
                    models.CharField(
                        choices=[("markdown", "Markdown"), ("text", "Plain text")],
                        default="markdown",
                        max_length=20,
                    ),
                ),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_important", models.BooleanField(default=False)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="study_workspace.studyresource",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_pinned", "timestamp_seconds", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudyBookmark",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("timestamp_seconds", models.PositiveIntegerField(default=0)),
                ("label", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                (
                    "bookmark_type",
                    models.CharField(
                        choices=[
                            ("important", "Important"),
                            ("difficult", "Difficult"),
                            ("review_later", "Review later"),
                            ("example", "Example"),
                            ("interview_point", "Interview point"),
                            ("custom", "Custom"),
                        ],
                        default="important",
                        max_length=30,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="study_workspace.studyresource",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp_seconds", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudySession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("last_transition_at", models.DateTimeField()),
                ("active_seconds", models.PositiveIntegerField(default=0)),
                ("paused_seconds", models.PositiveIntegerField(default=0)),
                ("idle_seconds", models.PositiveIntegerField(default=0)),
                ("session_goal", models.CharField(blank=True, max_length=240)),
                ("session_summary", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("ended", "Ended"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="study_sessions",
                        to="study_workspace.studyresource",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_sessions",
                        to="roadmaps.topic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="TopicStudyProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completion_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "confidence_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "difficulty_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("personal_summary", models.TextField(blank=True)),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_progress_records",
                        to="roadmaps.topic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_study_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VideoProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_position_seconds", models.PositiveIntegerField(default=0)),
                ("unique_watched_seconds", models.PositiveIntegerField(default=0)),
                (
                    "completion_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "playback_speed",
                    models.DecimalField(decimal_places=2, default=1, max_digits=3),
                ),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_watched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="study_workspace.studyresource",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WatchedInterval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_seconds", models.PositiveIntegerField()),
                ("end_seconds", models.PositiveIntegerField()),
                ("client_event_id", models.CharField(max_length=128)),
                (
                    "video_progress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watched_intervals",
                        to="study_workspace.videoprogress",
                    ),
                ),
            ],
            options={
                "ordering": ["start_seconds", "end_seconds"],
            },
        ),
        migrations.AddIndex(
            model_name="studyresource",
            index=models.Index(
                fields=["topic", "display_order"], name="study_works_topic_i_7c3fd1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="studyresource",
            constraint=models.UniqueConstraint(
                fields=("topic", "youtube_video_id"), name="unique_topic_youtube_video"
            ),
        ),
        migrations.AddIndex(
            model_name="studynote",
            index=models.Index(
                fields=["user", "resource", "timestamp_seconds"],
                name="study_works_user_id_66339c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studybookmark",
            index=models.Index(
                fields=["user", "resource", "timestamp_seconds"],
                name="study_works_user_id_b47e5e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studysession",
            index=models.Index(
                fields=["user", "status", "-started_at"],
                name="study_works_user_id_d026fd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="topicstudyprogress",
            index=models.Index(
                fields=["user", "completed", "-updated_at"],
                name="study_works_user_id_a6c7ec_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="topicstudyprogress",
            constraint=models.UniqueConstraint(
                fields=("user", "topic"), name="unique_user_topic_study_progress"
            ),
        ),
        migrations.AddIndex(
            model_name="videoprogress",
            index=models.Index(
                fields=["user", "-last_watched_at"],
                name="study_works_user_id_8beb54_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="videoprogress",
            constraint=models.UniqueConstraint(
                fields=("user", "resource"), name="unique_user_video_progress"
            ),
        ),
        migrations.AddConstraint(
            model_name="watchedinterval",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_seconds__gt", models.F("start_seconds"))),
                name="watched_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="watchedinterval",
            constraint=models.UniqueConstraint(
                fields=("video_progress", "client_event_id"),
                name="unique_progress_client_event",
            ),
        ),
    ]
