# Generated by Django 5.2.16 on 2026-07-22 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0001_initial'),
        ('study_workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studyresource',
            name='unique_topic_youtube_video',
        ),
        migrations.RemoveIndex(
            model_name='studyresource',
            name='study_works_topic_i_7c3fd1_idx',
        ),
        migrations.AlterField(
            model_name='studyresource',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_resources', to='roadmaps.topic'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_sessions', to='roadmaps.topic'),
        ),
        migrations.AddIndex(
            model_name='studyresource',
            index=models.Index(fields=['created_by', 'display_order'], name='study_works_created_e8f150_idx'),
        ),
        migrations.AddConstraint(
            model_name='studyresource',
            constraint=models.UniqueConstraint(fields=('created_by', 'youtube_video_id'), name='unique_user_youtube_video'),
        ),
    ]
