import {
  Activity, ArrowRight, BarChart3, BookOpenCheck, BrainCircuit, Braces, Check,
  CheckCircle2, Clock3, Code2, Compass, FileText, Goal, GraduationCap,
  Layers3, LockKeyhole, Play, Route, ShieldCheck, Sparkles, Target, TimerReset, Zap,
} from "lucide-react";
import Link from "next/link";

import { LandingThemeToggle } from "@/components/landing-theme-toggle";
import { Logo } from "@/components/logo";

const productFeatures = [
  { icon: Compass, title: "Adaptive roadmaps", text: "Build clear phases, modules, topics, resources, milestones, and measurable completion.", tone: "indigo" },
  { icon: TimerReset, title: "Focused study", text: "Run intentional sessions with video progress, notes, bookmarks, transcripts, and timers.", tone: "blue" },
  { icon: FileText, title: "Knowledge base", text: "Keep notes, documents, highlights, snippets, folders, and grounded search in one workspace.", tone: "violet" },
  { icon: Braces, title: "Code workspace", text: "Create versioned projects and execute twelve languages inside isolated, bounded containers.", tone: "slate" },
  { icon: Goal, title: "Outcome-driven goals", text: "Link measurable goals to roadmaps and projects, then track deadlines and progress.", tone: "emerald" },
  { icon: BarChart3, title: "Real analytics", text: "See study minutes, topic completion, project output, and goals—never invented activity.", tone: "amber" },
] as const;

const workflow = [
  { number: "01", icon: Target, title: "Choose the outcome", text: "Set a career, skill, habit, certification, or project goal with a clear target." },
  { number: "02", icon: Route, title: "Map the path", text: "Turn the outcome into ordered phases and focused topics with useful resources." },
  { number: "03", icon: Code2, title: "Study and build", text: "Capture evidence through focused sessions, durable knowledge, and real projects." },
  { number: "04", icon: Activity, title: "Measure and adapt", text: "Use honest analytics to decide what to continue, revise, or complete next." },
] as const;

const ticker = ["Roadmaps", "Study sessions", "Knowledge base", "Code execution", "Projects", "Goals", "Analytics", "Organizations"];

export default function Home() {
  return <main className="overflow-hidden bg-white text-slate-950 dark:bg-slate-950 dark:text-white">
    <header className="fixed inset-x-0 top-0 z-50 border-b border-white/60 bg-white/75 backdrop-blur-xl dark:border-slate-800/80 dark:bg-slate-950/75">
      <div className="mx-auto flex h-[4.5rem] max-w-7xl items-center px-5 sm:px-6">
        <Logo />
        <nav className="mx-auto hidden items-center gap-7 text-xs font-bold text-slate-500 lg:flex" aria-label="Primary navigation">
          <a href="#features" className="hover:text-indigo-600">Features</a><a href="#workflow" className="hover:text-indigo-600">How it works</a><a href="#security" className="hover:text-indigo-600">Security</a><Link href="/pricing" className="hover:text-indigo-600">Pricing</Link>
        </nav>
        <div className="ml-auto flex items-center gap-2"><LandingThemeToggle /><Link href="/login" className="hidden rounded-xl px-3 py-2.5 text-sm font-bold text-slate-600 hover:bg-slate-50 dark:text-slate-200 dark:hover:bg-slate-800 sm:block">Sign in</Link><Link href="/register" className="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-bold text-white shadow-lg shadow-indigo-500/20 hover:-translate-y-0.5 hover:bg-indigo-500">Start free</Link></div>
      </div>
    </header>

    <section className="relative px-5 pb-20 pt-32 sm:px-6 sm:pb-28 sm:pt-40">
      <div className="landing-grid absolute inset-0 opacity-50 dark:opacity-20" />
      <div className="landing-orb landing-orb-one" /><div className="landing-orb landing-orb-two" />
      <div className="relative mx-auto grid max-w-7xl items-center gap-16 lg:grid-cols-[.9fr_1.1fr]">
        <div className="relative z-10 text-center lg:text-left">
          <span className="landing-reveal inline-flex items-center gap-2 rounded-full border border-indigo-200 bg-indigo-50/80 px-3.5 py-1.5 text-[11px] font-black uppercase tracking-[.12em] text-indigo-700 shadow-sm dark:border-indigo-800 dark:bg-indigo-950/60 dark:text-indigo-300"><Sparkles size={13} /> Your learning operating system</span>
          <h1 className="landing-reveal landing-delay-1 mt-7 text-5xl font-black leading-[.98] tracking-[-.065em] text-slate-950 dark:text-white sm:text-7xl lg:text-[5rem]">Stop collecting courses. <span className="text-gradient">Start building capability.</span></h1>
          <p className="landing-reveal landing-delay-2 mx-auto mt-6 max-w-2xl text-base leading-8 text-slate-600 dark:text-slate-300 lg:mx-0 lg:max-w-xl">LearnOS connects goals, roadmaps, focused study, durable knowledge, coding projects, and honest analytics—so every hour moves toward an outcome.</p>
          <div className="landing-reveal landing-delay-3 mt-9 flex flex-col justify-center gap-3 sm:flex-row lg:justify-start"><Link href="/register" className="group inline-flex items-center justify-center gap-2 rounded-2xl bg-slate-950 px-6 py-4 text-sm font-black text-white shadow-2xl shadow-indigo-300/40 hover:-translate-y-1 dark:bg-white dark:text-slate-950 dark:shadow-indigo-950">Build your learning system <ArrowRight className="transition-transform group-hover:translate-x-1" size={17} /></Link><a href="#product" className="inline-flex items-center justify-center gap-2 rounded-2xl border border-slate-200 bg-white/80 px-6 py-4 text-sm font-black text-slate-700 shadow-sm backdrop-blur hover:-translate-y-1 hover:border-indigo-300 dark:border-slate-700 dark:bg-slate-900/80 dark:text-slate-200"><Play size={16} fill="currentColor" /> Explore the workspace</a></div>
          <div className="landing-reveal landing-delay-4 mt-8 flex flex-wrap justify-center gap-x-5 gap-y-2 text-[11px] font-bold text-slate-500 lg:justify-start"><span className="flex items-center gap-1.5"><CheckCircle2 size={14} className="text-emerald-500" /> Free workspace</span><span className="flex items-center gap-1.5"><CheckCircle2 size={14} className="text-emerald-500" /> Private by default</span><span className="flex items-center gap-1.5"><CheckCircle2 size={14} className="text-emerald-500" /> Real progress data</span></div>
        </div>

        <div id="product" className="landing-reveal landing-delay-2 relative mx-auto w-full max-w-2xl lg:max-w-none">
          <div className="landing-dashboard relative overflow-hidden rounded-[2rem] border border-slate-200/80 bg-white/90 p-3 shadow-[0_35px_100px_-30px_rgba(79,70,229,.38)] backdrop-blur dark:border-slate-700 dark:bg-slate-900/90">
            <div className="flex items-center gap-1.5 border-b border-slate-100 px-3 pb-3 dark:border-slate-800"><span className="size-2.5 rounded-full bg-rose-400" /><span className="size-2.5 rounded-full bg-amber-400" /><span className="size-2.5 rounded-full bg-emerald-400" /><span className="ml-3 rounded-md bg-slate-100 px-3 py-1 text-[8px] font-bold text-slate-400 dark:bg-slate-800">app.learnos.local/dashboard</span></div>
            <div className="grid min-h-[390px] grid-cols-[64px_1fr] sm:grid-cols-[150px_1fr]">
              <aside className="border-r border-slate-100 p-2.5 dark:border-slate-800"><span className="mx-auto grid size-8 place-items-center rounded-xl bg-indigo-600 text-white sm:mx-0"><GraduationCap size={15} /></span><div className="mt-6 grid gap-2">{["Overview", "Learning", "Projects", "Goals", "Analytics"].map((item, index) => <div key={item} className={`flex items-center gap-2 rounded-lg px-2 py-2 text-[8px] font-bold ${index === 0 ? "bg-indigo-50 text-indigo-700 dark:bg-indigo-950/60 dark:text-indigo-300" : "text-slate-400"}`}><span className={`size-1.5 rounded-full ${index === 0 ? "bg-indigo-500" : "bg-slate-300 dark:bg-slate-700"}`} /><span className="hidden sm:inline">{item}</span></div>)}</div></aside>
              <div className="min-w-0 bg-slate-50/70 p-4 dark:bg-slate-950/60 sm:p-5"><div className="flex items-start justify-between"><div><p className="text-[8px] font-black uppercase tracking-widest text-indigo-600">Personal workspace</p><h2 className="mt-1 text-base font-black sm:text-xl">Good morning, Learner.</h2></div><span className="grid size-8 place-items-center rounded-xl bg-violet-100 text-[9px] font-black text-violet-700 dark:bg-violet-950 dark:text-violet-300">LL</span></div>
                <div className="mt-5 grid grid-cols-3 gap-2"><MiniMetric icon={Clock3} value="192m" label="This week" /><MiniMetric icon={BookOpenCheck} value="3/10" label="Topics" /><MiniMetric icon={Goal} value="3" label="Goals" /></div>
                <div className="mt-3 grid gap-3 sm:grid-cols-[1.2fr_.8fr]"><div className="rounded-xl border border-slate-100 bg-white p-3 dark:border-slate-800 dark:bg-slate-900"><div className="flex justify-between"><div><p className="text-[8px] font-black">Full-Stack Engineer</p><p className="mt-1 text-[7px] text-slate-400">Continue your active roadmap</p></div><span className="text-[10px] font-black text-indigo-600">30%</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="landing-progress h-full rounded-full bg-gradient-to-r from-indigo-600 to-blue-500" /></div><div className="mt-4 grid gap-1.5">{["Semantic HTML", "Responsive CSS", "React component design"].map((topic, index) => <div key={topic} className="flex items-center gap-2 rounded-lg bg-slate-50 px-2 py-1.5 text-[7px] dark:bg-slate-800"><span className={`grid size-3.5 place-items-center rounded-full ${index < 2 ? "bg-emerald-500 text-white" : "border border-indigo-300"}`}>{index < 2 && <Check size={8} />}</span>{topic}</div>)}</div></div><div className="rounded-xl border border-slate-100 bg-white p-3 dark:border-slate-800 dark:bg-slate-900"><p className="text-[8px] font-black">Weekly focus</p><div className="mt-4 flex h-24 items-end gap-1.5">{[35,58,28,82,48,70,42].map((height, index) => <span key={index} className="landing-bar flex-1 rounded-t bg-gradient-to-t from-indigo-600 to-violet-400" style={{ height: `${height}%`, animationDelay: `${index * 90}ms` }} />)}</div><div className="mt-2 flex justify-between text-[6px] font-bold text-slate-400"><span>M</span><span>T</span><span>W</span><span>T</span><span>F</span><span>S</span><span>S</span></div></div></div>
              </div>
            </div>
          </div>
          <div className="landing-float absolute -left-4 top-28 hidden rounded-2xl border border-emerald-200 bg-white/95 p-3 shadow-xl dark:border-emerald-900 dark:bg-slate-900 sm:block"><div className="flex items-center gap-2"><span className="grid size-8 place-items-center rounded-xl bg-emerald-100 text-emerald-600 dark:bg-emerald-950"><CheckCircle2 size={16} /></span><div><strong className="block text-[9px]">Goal updated</strong><span className="text-[7px] text-slate-400">2 of 3 projects shipped</span></div></div></div>
          <div className="landing-float landing-float-late absolute -bottom-5 right-2 rounded-2xl border border-violet-200 bg-slate-950 p-3 text-white shadow-xl dark:border-violet-800"><div className="flex items-center gap-2"><span className="grid size-8 place-items-center rounded-xl bg-violet-500/20 text-violet-300"><Code2 size={16} /></span><div><strong className="block text-[9px]">Execution succeeded</strong><span className="text-[7px] text-slate-400">Python · 248ms · isolated</span></div></div></div>
        </div>
      </div>
    </section>

    <div className="border-y border-slate-200 bg-slate-950 py-3 text-white dark:border-slate-800"><div className="landing-marquee flex w-max items-center gap-8 pr-8">{[...ticker, ...ticker].map((item, index) => <span key={`${item}-${index}`} className="flex items-center gap-2 whitespace-nowrap text-[10px] font-black uppercase tracking-[.16em] text-slate-300"><Zap size={11} className="text-violet-400" />{item}</span>)}</div></div>

    <section className="px-5 py-20 sm:px-6 sm:py-28"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-4 md:grid-cols-4"><Proof value="12" label="execution languages" /><Proof value="7" label="connected workspaces" /><Proof value="1" label="source of progress truth" /><Proof value="0" label="fake activity metrics" /></div></section>

    <section id="features" className="relative bg-slate-50 px-5 py-20 dark:bg-slate-900/40 sm:px-6 sm:py-28"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="One connected system" title="Everything your learning needs to become useful." text="Each workspace is powerful alone. Together, they keep intention, practice, knowledge, and evidence connected." /><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{productFeatures.map(({ icon: Icon, title, text, tone }, index) => <article key={title} className="landing-feature group relative overflow-hidden rounded-3xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900" style={{ animationDelay: `${index * 100}ms` }}><div className={`feature-glow feature-glow-${tone}`} /><span className={`relative grid size-12 place-items-center rounded-2xl feature-${tone}`}><Icon size={22} /></span><h3 className="relative mt-6 text-lg font-black tracking-tight">{title}</h3><p className="relative mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">{text}</p><span className="relative mt-6 inline-flex items-center gap-1 text-[10px] font-black uppercase tracking-wider text-indigo-600 opacity-0 transition-all group-hover:translate-x-1 group-hover:opacity-100">Explore capability <ArrowRight size={12} /></span></article>)}</div></div></section>

    <section id="workflow" className="px-5 py-20 sm:px-6 sm:py-28"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="From ambition to evidence" title="A repeatable learning loop." text="LearnOS keeps the next action close while preserving the bigger outcome." /><div className="relative mt-14 grid gap-5 md:grid-cols-2 lg:grid-cols-4"><div className="absolute left-[12%] right-[12%] top-7 hidden border-t border-dashed border-indigo-200 lg:block dark:border-indigo-900" />{workflow.map(({ number, icon: Icon, title, text }) => <article key={number} className="relative rounded-3xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><span className="relative z-10 grid size-14 place-items-center rounded-2xl bg-indigo-600 text-white shadow-lg shadow-indigo-300/40 dark:shadow-none"><Icon size={22} /></span><span className="absolute right-5 top-4 text-4xl font-black text-slate-100 dark:text-slate-800">{number}</span><h3 className="mt-6 font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">{text}</p></article>)}</div></div></section>

    <section id="security" className="px-5 pb-20 sm:px-6 sm:pb-28"><div className="relative mx-auto max-w-7xl overflow-hidden rounded-[2rem] bg-slate-950 px-6 py-12 text-white sm:px-10 lg:px-14 lg:py-16"><div className="absolute -right-24 -top-24 size-80 rounded-full bg-violet-600/20 blur-3xl" /><div className="relative grid items-center gap-10 lg:grid-cols-[1fr_.8fr]"><div><span className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[.16em] text-violet-300"><LockKeyhole size={14} /> Built to fail closed</span><h2 className="mt-4 max-w-2xl text-3xl font-black tracking-[-.04em] sm:text-5xl">Professional learning needs professional boundaries.</h2><p className="mt-5 max-w-2xl text-sm leading-7 text-slate-300">Tenant-aware access, private-by-default data, versioned code, auditable actions, and isolated execution keep experimentation useful without making security an afterthought.</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-1">{[[ShieldCheck,"Owner-scoped access"],[Layers3,"Organization isolation"],[Code2,"No-network code sandboxes"],[BrainCircuit,"Grounded AI workflows"]].map(([Icon, label]) => { const ItemIcon = Icon as typeof ShieldCheck; return <div key={label as string} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/5 p-4 backdrop-blur"><span className="grid size-9 place-items-center rounded-xl bg-emerald-500/15 text-emerald-300"><ItemIcon size={17} /></span><strong className="text-xs">{label as string}</strong></div>; })}</div></div></div></section>

    <section className="px-5 pb-20 sm:px-6 sm:pb-28"><div className="landing-cta relative mx-auto max-w-7xl overflow-hidden rounded-[2rem] border border-indigo-200 bg-gradient-to-br from-indigo-50 via-white to-violet-50 px-6 py-14 text-center dark:border-indigo-900 dark:from-indigo-950/60 dark:via-slate-900 dark:to-violet-950/50 sm:px-10 sm:py-20"><div className="landing-orbit"><span /><span /><span /></div><div className="relative"><span className="inline-flex items-center gap-2 rounded-full bg-white px-3 py-1.5 text-[10px] font-black uppercase tracking-wider text-indigo-700 shadow-sm dark:bg-slate-900 dark:text-indigo-300"><Sparkles size={12} /> Your next chapter can be measurable</span><h2 className="mx-auto mt-5 max-w-3xl text-4xl font-black tracking-[-.05em] sm:text-6xl">Build a learning system that compounds.</h2><p className="mx-auto mt-5 max-w-xl text-sm leading-7 text-slate-600 dark:text-slate-300">Start with one goal. Leave with a roadmap, a practice loop, durable knowledge, and proof of progress.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/register" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-indigo-600 px-6 py-4 text-sm font-black text-white shadow-xl shadow-indigo-300/40 hover:-translate-y-1 dark:shadow-none">Create your workspace <ArrowRight size={17} /></Link><Link href="/login" className="inline-flex items-center justify-center rounded-2xl border border-slate-200 bg-white px-6 py-4 text-sm font-black text-slate-700 hover:-translate-y-1 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200">Sign in</Link></div></div></div></section>

    <footer className="border-t border-slate-200 px-5 py-8 dark:border-slate-800 sm:px-6"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-5 sm:flex-row"><Logo /><p className="text-center text-[11px] leading-5 text-slate-400">A private, outcome-driven learning operating system.</p><div className="flex gap-5 text-[11px] font-bold text-slate-500"><a href="#features">Features</a><Link href="/pricing">Pricing</Link><Link href="/login">Sign in</Link></div></div></footer>
  </main>;
}

function MiniMetric({ icon: Icon, value, label }: { icon: typeof Clock3; value: string; label: string }) { return <div className="rounded-xl border border-slate-100 bg-white p-2.5 dark:border-slate-800 dark:bg-slate-900"><Icon size={11} className="text-indigo-600" /><strong className="mt-2 block text-xs">{value}</strong><span className="text-[6px] uppercase tracking-wide text-slate-400">{label}</span></div>; }
function Proof({ value, label }: { value: string; label: string }) { return <div className="text-center"><strong className="block text-4xl font-black tracking-[-.06em] text-slate-950 dark:text-white sm:text-5xl">{value}</strong><span className="mt-2 block text-[10px] font-black uppercase tracking-[.14em] text-slate-400">{label}</span></div>; }
function SectionHeading({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <div className="mx-auto max-w-3xl text-center"><p className="text-[10px] font-black uppercase tracking-[.18em] text-indigo-600">{eyebrow}</p><h2 className="mt-4 text-3xl font-black tracking-[-.045em] text-slate-950 dark:text-white sm:text-5xl">{title}</h2><p className="mx-auto mt-4 max-w-2xl text-sm leading-7 text-slate-500 dark:text-slate-400">{text}</p></div>; }
