"use client";

import { Braces, Clock3, Code2, FileCode2, Plus, Search, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useMemo, useState } from "react";
import { CodeAppLayout } from "@/components/code/app-layout";
import { CreateProjectDialog } from "@/components/code/create-project-dialog";
import { api } from "@/lib/api";
import type { CodingProjectDetail, CodingProjectSummary, User } from "@/lib/types";

const languageColors: Record<string, string> = { python: "bg-blue-50 text-blue-700", javascript: "bg-amber-50 text-amber-700", typescript: "bg-sky-50 text-sky-700", react: "bg-cyan-50 text-cyan-700", java: "bg-orange-50 text-orange-700", rust: "bg-rose-50 text-rose-700" };

export default function CodeProjectsPage() {
  const router = useRouter();
  const [user, setUser] = useState<User | null>(null);
  const [projects, setProjects] = useState<CodingProjectSummary[]>([]);
  const [query, setQuery] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [creating, setCreating] = useState(false);
  const load = useCallback(async () => { try { const [me, items] = await Promise.all([api<User>("/me/"), api<CodingProjectSummary[]>("/coding/projects/")]); setUser(me); setProjects(items); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load coding projects"); } finally { setLoading(false); } }, []);
  useEffect(() => { const task = window.setTimeout(() => void load(), 0); return () => clearTimeout(task); }, [load]);
  const filtered = useMemo(() => projects.filter(project => `${project.name} ${project.description} ${project.primary_language}`.toLowerCase().includes(query.toLowerCase())), [projects, query]);

  return <CodeAppLayout user={user}><div className="mx-auto max-w-7xl p-5 pb-12 sm:p-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.15em] text-violet-600"><span className="h-px w-5 bg-violet-500" /> Build and practice</div><h1 className="mt-3 text-3xl font-black tracking-[-.045em] text-slate-950 sm:text-4xl">Code workspace</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Write and organize code with a professional browser editor. Files are versioned and private to your account.</p></div><button onClick={() => setCreating(true)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-violet-600 px-4 py-3 text-sm font-bold text-white shadow-lg shadow-violet-200"><Plus size={17} /> New project</button></div>
    <section className="mt-8 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white p-5"><Code2 className="text-violet-600" size={19} /><strong className="mt-3 block text-3xl font-black">{projects.length}</strong><span className="text-xs text-slate-500">Coding projects</span></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><FileCode2 className="text-blue-600" size={19} /><strong className="mt-3 block text-3xl font-black">{projects.reduce((sum, project) => sum + project.file_count, 0)}</strong><span className="text-xs text-slate-500">Versioned files</span></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><ShieldCheck className="text-emerald-600" size={19} /><strong className="mt-3 block text-lg font-black">Private by default</strong><span className="text-xs text-slate-500">Owner-scoped project access</span></div></section>
    <div className="mt-6 flex items-center rounded-2xl border border-slate-200 bg-white p-3"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={17} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search projects or languages" className="w-full rounded-xl border-0 bg-slate-50 py-2.5 pl-10 pr-3 text-sm outline-none ring-violet-100 focus:ring-2" /></div></div>
    {error && <p className="mt-5 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}
    {loading ? <div className="mt-6 grid animate-pulse gap-4 md:grid-cols-2 xl:grid-cols-3">{[1,2,3].map(item => <div key={item} className="h-56 rounded-2xl bg-white ring-1 ring-slate-200" />)}</div> : filtered.length ? <section className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(project => <Link href={`/code/${project.id}`} key={project.id} className="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-violet-200 hover:shadow-xl hover:shadow-violet-100/50"><div className="flex items-start justify-between"><span className="grid size-11 place-items-center rounded-xl bg-slate-950 text-violet-300"><Braces size={21} /></span><span className={`rounded-full px-2.5 py-1 text-[9px] font-black uppercase ${languageColors[project.primary_language] || "bg-slate-100 text-slate-600"}`}>{project.primary_language}</span></div><h2 className="mt-5 text-lg font-black tracking-tight group-hover:text-violet-700">{project.name}</h2><p className="mt-2 line-clamp-2 min-h-10 text-xs leading-5 text-slate-500">{project.description || "Open the workspace and start building."}</p><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4 text-[10px] text-slate-400"><span className="flex items-center gap-1"><FileCode2 size={12} /> {project.file_count} files</span><span className="flex items-center gap-1"><Clock3 size={12} /> Updated {new Intl.DateTimeFormat(undefined,{month:"short",day:"numeric"}).format(new Date(project.updated_at))}</span></div></Link>)}</section> : <section className="mt-6 rounded-3xl border border-dashed border-slate-300 bg-white px-6 py-16 text-center"><span className="mx-auto grid size-16 place-items-center rounded-2xl bg-violet-50 text-violet-600"><Braces size={28} /></span><h2 className="mt-5 text-xl font-black">{query ? "No matching projects" : "Create your first project"}</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">{query ? "Try another name or language." : "Choose a language and LearnOS will create a starter workspace with versioned files."}</p>{!query && <button onClick={() => setCreating(true)} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-violet-600 px-4 py-3 text-sm font-bold text-white"><Plus size={17} /> New project</button>}</section>}
    <CreateProjectDialog open={creating} onClose={() => setCreating(false)} onCreated={(project: CodingProjectDetail) => { setCreating(false); router.push(`/code/${project.id}`); }} /></div></CodeAppLayout>;
}
