"use client";

import { BarChart3, BookOpenCheck, CheckCircle2, Clock3, FolderKanban, Goal } from "lucide-react";
import { useEffect, useState } from "react";

import { AppLayout } from "@/components/app-layout";
import { api } from "@/lib/api";
import type { LearningAnalytics, User } from "@/lib/types";

export default function AnalyticsPage() {
  const [user, setUser] = useState<User | null>(null); const [data, setData] = useState<LearningAnalytics | null>(null); const [error, setError] = useState("");
  useEffect(() => { void Promise.all([api<User>("/me/"), api<LearningAnalytics>("/analytics/")]).then(([me, result]) => { setUser(me); setData(result); }).catch(reason => setError(reason instanceof Error ? reason.message : "Could not load analytics")); }, []);
  const maxMinutes = Math.max(1, ...(data?.weekly_activity.map(item => item.minutes) ?? [1]));
  return <AppLayout user={user} currentPath="/analytics"><div className="mx-auto max-w-7xl p-5 pb-12 sm:p-8"><div><p className="text-xs font-black uppercase tracking-[.15em] text-blue-600">Evidence, not vanity metrics</p><h1 className="mt-3 text-3xl font-black tracking-[-.045em]">Learning analytics</h1><p className="mt-2 text-sm text-slate-500">Real activity from study sessions, roadmap progress, goals, and projects.</p></div>{error && <p className="mt-5 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}
    <section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Clock3} label="Total study time" value={`${data?.overview.total_study_minutes ?? 0} min`} /><Metric icon={CheckCircle2} label="Topics complete" value={`${data?.overview.completed_topics ?? 0}/${data?.overview.total_topics ?? 0}`} /><Metric icon={FolderKanban} label="Projects" value={String(data?.overview.projects ?? 0)} /><Metric icon={Goal} label="Goals achieved" value={`${data?.overview.completed_goals ?? 0}/${data?.overview.total_goals ?? 0}`} /></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><article className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center justify-between"><div><h2 className="font-black">Study activity</h2><p className="mt-1 text-xs text-slate-500">Focused minutes during the last seven days.</p></div><BarChart3 className="text-blue-600" size={20} /></div><div className="mt-8 flex h-56 items-end gap-3">{data?.weekly_activity.map(item => <div key={item.date} className="flex h-full flex-1 flex-col justify-end text-center"><span className="mb-2 text-[10px] font-bold text-slate-500">{item.minutes || ""}</span><div className="min-h-1 rounded-t-lg bg-gradient-to-t from-blue-600 to-indigo-400" style={{ height: `${Math.max(3, item.minutes / maxMinutes * 100)}%` }} /><span className="mt-2 text-[10px] font-bold text-slate-400">{new Intl.DateTimeFormat(undefined, { weekday: "short" }).format(new Date(`${item.date}T00:00:00`))}</span></div>)}</div></article>
      <article className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center justify-between"><div><h2 className="font-black">Roadmap progress</h2><p className="mt-1 text-xs text-slate-500">Completion across owned learning paths.</p></div><BookOpenCheck className="text-indigo-600" size={20} /></div><div className="mt-6 grid gap-4">{data?.roadmaps.slice(0, 6).map(item => <div key={item.id}><div className="flex justify-between gap-3 text-xs"><strong className="truncate">{item.title}</strong><span className="font-black text-indigo-600">{item.progress_percentage}%</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-indigo-600" style={{ width: `${item.progress_percentage}%` }} /></div><p className="mt-1 text-[9px] text-slate-400">{item.completed_topic_count}/{item.topic_count} topics</p></div>)}{data && !data.roadmaps.length && <p className="rounded-xl border border-dashed border-slate-200 p-8 text-center text-xs text-slate-400">Create a roadmap to begin measuring progress.</p>}</div></article></section>
  </div></AppLayout>;
}
function Metric({ icon: Icon, label, value }: { icon: typeof Clock3; label: string; value: string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5"><Icon size={18} className="text-blue-600" /><strong className="mt-3 block text-2xl font-black">{value}</strong><span className="text-xs text-slate-500">{label}</span></div>; }

