"use client";

import { Check, CircleAlert, Goal, LoaderCircle, Plus, Target, Trash2, X } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";

import { AppLayout } from "@/components/app-layout";
import { api } from "@/lib/api";
import type { LearningGoal, RoadmapSummary, User } from "@/lib/types";

export default function GoalsPage() {
  const [user, setUser] = useState<User | null>(null); const [goals, setGoals] = useState<LearningGoal[]>([]); const [roadmaps, setRoadmaps] = useState<RoadmapSummary[]>([]);
  const [creating, setCreating] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [formError, setFormError] = useState("");
  async function load() { try { const [me, items, maps] = await Promise.all([api<User>("/me/"), api<LearningGoal[]>("/goals/"), api<RoadmapSummary[]>("/roadmaps/")]); setUser(me); setGoals(items); setRoadmaps(maps.filter(item => item.is_owner)); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load goals"); } }
  useEffect(() => { const task = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(task); }, []);
  async function createGoal(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setFormError(""); const form = new FormData(event.currentTarget); try { await api("/goals/", { method: "POST", body: JSON.stringify({ title: String(form.get("title") || "").trim(), description: String(form.get("description") || "").trim(), category: form.get("category"), priority: form.get("priority"), status: "in_progress", target_value: Number(form.get("target_value")), unit: String(form.get("unit") || "percent").trim(), target_date: form.get("target_date") || null, roadmap: form.get("roadmap") || null }) }); setCreating(false); await load(); } catch (reason) { setFormError(reason instanceof Error ? reason.message : "Could not create goal"); } finally { setSaving(false); } }
  async function update(goal: LearningGoal, payload: Record<string, unknown>) { try { await api(`/goals/${goal.id}/`, { method: "PATCH", body: JSON.stringify(payload) }); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not update goal"); } }
  async function remove(goal: LearningGoal) { if (!window.confirm(`Delete “${goal.title}”?`)) return; await api(`/goals/${goal.id}/`, { method: "DELETE" }); await load(); }
  const completed = goals.filter(goal => goal.status === "completed").length;
  return <AppLayout user={user} currentPath="/goals"><div className="mx-auto max-w-7xl p-5 pb-12 sm:p-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-black uppercase tracking-[.15em] text-emerald-600">Outcome management</p><h1 className="mt-3 text-3xl font-black tracking-[-.045em]">Goals</h1><p className="mt-2 text-sm text-slate-500">Turn ambitions into measurable outcomes linked to your roadmaps.</p></div><button onClick={() => { setFormError(""); setCreating(true); }} className="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-600 px-4 py-3 text-sm font-bold text-white"><Plus size={17} /> New goal</button></div>
    <section className="mt-8 grid gap-4 sm:grid-cols-3"><Stat label="Total goals" value={goals.length} /><Stat label="In progress" value={goals.filter(goal => goal.status === "in_progress").length} /><Stat label="Completed" value={completed} /></section>{error && <p className="mt-5 flex items-center gap-2 rounded-xl bg-rose-50 p-3 text-sm text-rose-700"><CircleAlert size={16} />{error}</p>}
    <section className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{goals.map(goal => <article key={goal.id} className={`rounded-2xl border bg-white p-5 ${goal.is_overdue ? "border-rose-200" : "border-slate-200"}`}><div className="flex items-start justify-between"><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[9px] font-black uppercase text-emerald-700">{goal.category}</span><button onClick={() => void remove(goal)} className="text-slate-300 hover:text-rose-600" aria-label="Delete goal"><Trash2 size={15} /></button></div><h2 className="mt-4 font-black">{goal.title}</h2><p className="mt-1 line-clamp-2 min-h-10 text-xs leading-5 text-slate-500">{goal.description || goal.roadmap_title || "Personal learning goal"}</p><div className="mt-4 flex justify-between text-[10px] font-bold"><span>{goal.current_value} / {goal.target_value} {goal.unit}</span><span>{goal.progress_percentage}%</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-500" style={{ width: `${goal.progress_percentage}%` }} /></div><div className="mt-4 flex gap-2"><button disabled={goal.status === "completed"} onClick={() => void update(goal, { current_value: Math.min(goal.target_value, goal.current_value + Math.max(1, Math.ceil(goal.target_value / 10))), status: "in_progress" })} className="flex-1 rounded-lg border border-slate-200 py-2 text-[10px] font-bold disabled:opacity-40">Add progress</button><button onClick={() => void update(goal, { status: goal.status === "completed" ? "in_progress" : "completed" })} className="grid size-8 place-items-center rounded-lg bg-emerald-600 text-white" title="Toggle complete"><Check size={14} /></button></div>{goal.is_overdue && <p className="mt-3 text-[10px] font-bold text-rose-600">Past target date</p>}</article>)}{!goals.length && <div className="col-span-full rounded-3xl border border-dashed border-slate-300 bg-white p-14 text-center"><Target className="mx-auto text-slate-300" size={32} /><h2 className="mt-4 font-black">Define your first measurable goal</h2><button onClick={() => setCreating(true)} className="mt-3 text-sm font-bold text-emerald-600">Create goal</button></div>}</section>
    {creating && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><form onSubmit={createGoal} className="max-h-[92vh] w-full max-w-xl overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><h2 className="text-lg font-black">Create a goal</h2><p className="text-xs text-slate-500">Make the outcome specific and measurable.</p></div><button type="button" onClick={() => setCreating(false)}><X size={18} /></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="grid-field sm:col-span-2"><span>Goal title</span><input name="title" required maxLength={180} autoFocus placeholder="Example: Complete 10 backend topics" /></label><label className="grid-field sm:col-span-2"><span>Description</span><textarea name="description" rows={3} /></label><label className="grid-field"><span>Category</span><select name="category"><option value="skill">Skill</option><option value="project">Project</option><option value="career">Career</option><option value="certification">Certification</option><option value="habit">Habit</option></select></label><label className="grid-field"><span>Priority</span><select name="priority"><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></label><label className="grid-field"><span>Target</span><input name="target_value" type="number" min="1" defaultValue="100" required /></label><label className="grid-field"><span>Unit</span><input name="unit" defaultValue="percent" maxLength={40} required /></label><label className="grid-field"><span>Target date</span><input name="target_date" type="date" min={new Date().toISOString().slice(0, 10)} /></label><label className="grid-field"><span>Roadmap</span><select name="roadmap"><option value="">None</option>{roadmaps.map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label></div>{formError && <p role="alert" className="mt-4 flex items-center gap-2 rounded-xl border border-rose-200 bg-rose-50 p-3 text-xs font-semibold text-rose-700"><CircleAlert size={15} />{formError}</p>}<button disabled={saving} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-600 py-3 text-sm font-bold text-white disabled:opacity-60">{saving && <LoaderCircle className="animate-spin" size={16} />} {saving ? "Creating goal…" : "Create goal"}</button></form></div>}
  </div></AppLayout>;
}
function Stat({ label, value }: { label: string; value: number }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5"><Goal size={17} className="text-emerald-600" /><strong className="mt-3 block text-3xl font-black">{value}</strong><span className="text-xs text-slate-500">{label}</span></div>; }
