# Generated by Django 5.2.16 on 2026-07-21 19:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('primary_language', models.CharField(default='python', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coding_projects', to='organizations.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True)),
                ('language', models.CharField(default='plaintext', max_length=30)),
                ('version', models.PositiveIntegerField(default=1)),
                ('checksum', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='coding.codingproject')),
            ],
            options={
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFileRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('content', models.TextField(blank=True)),
                ('checksum', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='code_revisions', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='coding.projectfile')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddIndex(
            model_name='codingproject',
            index=models.Index(fields=['owner', 'status', '-updated_at'], name='coding_codi_owner_i_1ae6d2_idx'),
        ),
        migrations.AddIndex(
            model_name='projectfile',
            index=models.Index(fields=['project', 'path'], name='coding_proj_project_e752f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectfile',
            constraint=models.UniqueConstraint(fields=('project', 'path'), name='unique_project_file_path'),
        ),
        migrations.AddConstraint(
            model_name='projectfilerevision',
            constraint=models.UniqueConstraint(fields=('file', 'version'), name='unique_file_revision_version'),
        ),
    ]
