# Generated by Django 5.2.16 on 2026-07-22 04:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(max_length=30)),
                ('source_snapshot', models.TextField()),
                ('stdin', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('dispatching', 'Dispatching'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timed_out', 'Timed out')], default='queued', max_length=20)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('controller_job_id', models.CharField(blank=True, db_index=True, max_length=160)),
                ('limits', models.JSONField(default=dict)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('runtime_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('memory_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_jobs', to='coding.codingproject')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_jobs', to=settings.AUTH_USER_MODEL)),
                ('source_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_jobs', to='coding.projectfile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['requested_by', 'status', '-created_at'], name='coding_exec_request_af7a40_idx'), models.Index(fields=['project', '-created_at'], name='coding_exec_project_3edff3_idx')],
                'constraints': [models.UniqueConstraint(fields=('requested_by', 'idempotency_key'), name='unique_execution_idempotency_key')],
            },
        ),
    ]
