from django.urls import path

from .views import (
    AIActionView,
    AskView,
    DocumentContentView,
    DocumentDetailView,
    DocumentListView,
    DocumentTextView,
    FolderDetailView,
    FolderListView,
    HighlightListView,
    HighlightDetailView,
    KnowledgeDashboardView,
    NoteDetailView,
    NoteListView,
    NoteVersionListView,
    SearchView,
    SnippetDetailView,
    SnippetListView,
    TagListView,
    TagDetailView,
)

urlpatterns = [
    path("knowledge/", KnowledgeDashboardView.as_view(), name="knowledge-dashboard"),
    path("knowledge/folders/", FolderListView.as_view(), name="knowledge-folder-list"),
    path("knowledge/folders/<uuid:folder_id>/", FolderDetailView.as_view(), name="knowledge-folder-detail"),
    path("knowledge/tags/", TagListView.as_view(), name="knowledge-tag-list"),
    path("knowledge/tags/<uuid:tag_id>/", TagDetailView.as_view(), name="knowledge-tag-detail"),
    path("knowledge/notes/", NoteListView.as_view(), name="knowledge-note-list"),
    path("knowledge/notes/<uuid:note_id>/", NoteDetailView.as_view(), name="knowledge-note-detail"),
    path("knowledge/notes/<uuid:note_id>/versions/", NoteVersionListView.as_view(), name="knowledge-note-versions"),
    path("knowledge/documents/", DocumentListView.as_view(), name="knowledge-document-list"),
    path("knowledge/documents/<uuid:document_id>/", DocumentDetailView.as_view(), name="knowledge-document-detail"),
    path("knowledge/documents/<uuid:document_id>/content/", DocumentContentView.as_view(), name="knowledge-document-content"),
    path("knowledge/documents/<uuid:document_id>/text/", DocumentTextView.as_view(), name="knowledge-document-text"),
    path("knowledge/documents/<uuid:document_id>/highlights/", HighlightListView.as_view(), name="knowledge-highlight-list"),
    path("knowledge/highlights/<uuid:highlight_id>/", HighlightDetailView.as_view(), name="knowledge-highlight-detail"),
    path("knowledge/snippets/", SnippetListView.as_view(), name="knowledge-snippet-list"),
    path("knowledge/snippets/<uuid:snippet_id>/", SnippetDetailView.as_view(), name="knowledge-snippet-detail"),
    path("knowledge/search/", SearchView.as_view(), name="knowledge-search"),
    path("knowledge/ask/", AskView.as_view(), name="knowledge-ask"),
    path("knowledge/ai-actions/", AIActionView.as_view(), name="knowledge-ai-action"),
]
